### ISSUE TITLE
Throws Error when run 

### ISSUE THREAD

**Issue by giannif** [WorkFlowWise/typedoc-plugin-explicit-include#1]
I'm getting this error when trying to use the plugin:
```
Error: The plugin <myproject>/node_modules/typedoc-plugin-explicit-include could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
    at new ExplicitIncludePlugin (<myproject>/node_modules/typedoc-plugin-explicit-include/plugin.js:40:51)
    at Converter.addComponent (<myproject>/node_modules/typedoc/dist/lib/utils/component.js:123:19)
    at Converter.addComponent (<myproject>/node_modules/typedoc/dist/lib/converter/converter.js:28:33)
    at module.exports (<myproject>/node_modules/typedoc-plugin-explicit-include/index.js:5:17)
    at PluginHost.load (<myproject>/node_modules/typedoc/dist/lib/utils/plugins.js:36:21)
    at CliApplication.bootstrap (<myproject>/node_modules/typedoc/dist/lib/application.js:42:22)
    at CliApplication.bootstrap (<myproject>/node_modules/typedoc/dist/lib/cli.js:24:30)
    at new Application (<myproject>/node_modules/typedoc/dist/lib/application.js:31:14)
    at new CliApplication (<myproject>/node_modules/typedoc/dist/lib/cli.js:22:1)
    at Object.<anonymous> (<myproject>/node_modules/typedoc/bin/typedoc:4:1)

Using TypeScript 3.2.4 from <myproject>/node_modules/typedoc/node_modules/typescript/lib
Rendering [========================================] 100%
Error: Documentation could not be generated due to the errors above.
```

**Comment by giannif** [comment]
I recompiled `plugin.ts` locally with a newer version of typescript and the error went away

**Comment by LydGol90** [comment]
@giannif I am seeing the same error as above. Have you forked the repo or anything? Thanks
